language: node_js
node_js:
  - "6.10"

sudo: required
dist: trusty
cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:

script:
  # - npm run test
  - ng build --target production --aot --build-optimizer --vendor-chunk --extract-css --output-hashing all

deploy:
  provider: pages
  repo: Cabeda/Cabeda.github.io
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: master

notifications:
  slack: lhasau:vgGqEnPhI0K9CCSCzGrv7fZs
