language: node_js
node_js:
  - "6.9.2"
branches:
  only:
    - master
sudo: required
before_script:
  - npm install -g angular-cli
  # - ./scripts/setup-github-access.sh

script:
  # - npm run test
  - ng build --prod

after_success:
  # - ./scripts/remove-branch.sh
  -sudo ./scripts/.travis-deploy.sh

notifications:
  email:
    on_failure: change
    on_success: change