language: node_js
node_js:
  - "6.9.2"
branches:
  only:
    - master

before_script:
  - npm install -g angular-cli
  - ./scripts/setup-github-access.sh

script:
  - ng build --prod

after_success:
  - ./scripts/remove-branch.sh
  - npm run deploy-gh-pages

notifications:
  email:
    on_failure: change
    on_success: change