language: node_js
node_js:
  - "6.9.2"

sudo: required
dist: trusty
cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  # - npm install -g angular-cli
  # - ./scripts/setup-github-access.sh

script:
  # - npm run test
  - ng build --prod

after_success:
  # - ./scripts/remove-branch.sh
  - chmod ugo+x scripts/.travis-deploy.sh
  - ./scripts/.travis-deploy.sh
  - git push --force -- quiet"https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1

notifications:
  email:
    on_failure: change
    on_success: change