language: node_js
node_js:
  - "6.9.2"
branches:
  only:
    - master

before_script:
  - npm install -g angular-cli
  # - ./scripts/setup-github-access.sh

script:
  # - npm run test
  - ng build --prod

after_success:
- git config --global user.email "jecabeda@gmail.com"
- git config --global user.name "cabeda"
- npm run release
- cd dist
- git init
- git add .
- git commit -m "deployed new version from travis"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
  # - ./scripts/remove-branch.sh
  # - npm run deploy-gh-pages

notifications:
  email:
    on_failure: change
    on_success: change